#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/demo_env.sh"
require_runtime

export MATRIX_ROBOT_INITIAL_X="${MATRIX_ROBOT_INITIAL_X:-0.2}"
export MATRIX_ROBOT_INITIAL_Y="${MATRIX_ROBOT_INITIAL_Y:-0.0}"
export MATRIX_ROBOT_INITIAL_YAW_DEG="${MATRIX_ROBOT_INITIAL_YAW_DEG:-90}"
export MATRIX_UE_OFFSCREEN="${MATRIX_UE_OFFSCREEN:-0}"
export MATRIX_UE_NO_RHI_THREAD="${MATRIX_UE_NO_RHI_THREAD:-0}"
export MATRIX_CAMERA_FREQUENCY="${MATRIX_CAMERA_FREQUENCY:-5}"
export MATRIX_CAMERA_WIDTH="${MATRIX_CAMERA_WIDTH:-960}"
export MATRIX_CAMERA_HEIGHT="${MATRIX_CAMERA_HEIGHT:-540}"
export MATRIX_DISABLE_IMAGE_SENSORS=0
export MATRIX_SKIP_STALE_PROCESS_CLEANUP="${MATRIX_SKIP_STALE_PROCESS_CLEANUP:-1}"
export GO2W_RL_STOCHASTIC="${GO2W_RL_STOCHASTIC:-1}"
export GO2W_RL_STAIR_OBSTACLE_AVOIDANCE="${GO2W_RL_STAIR_OBSTACLE_AVOIDANCE:-1}"
export GO2W_RL_STAIR_PLANNER_YAW_BLEND="${GO2W_RL_STAIR_PLANNER_YAW_BLEND:-0.90}"
export GO2W_RL_STAIR_PLANNER_CENTERING_SCALE="${GO2W_RL_STAIR_PLANNER_CENTERING_SCALE:-0.25}"
export GO2W_RL_STAIR_PLANNER_MIN_VX="${GO2W_RL_STAIR_PLANNER_MIN_VX:-0.18}"
export GO2W_RL_STAIR_PLANNER_MAX_VX="${GO2W_RL_STAIR_PLANNER_MAX_VX:-0.80}"
export GO2W_RL_STAIR_PLANNER_TURN_THRESHOLD="${GO2W_RL_STAIR_PLANNER_TURN_THRESHOLD:-0.06}"
export GO2W_RL_STAIR_OBSTACLE_MIN_Y="${GO2W_RL_STAIR_OBSTACLE_MIN_Y:-2.55}"
export GO2W_RL_STAIR_OBSTACLE_MAX_Y="${GO2W_RL_STAIR_OBSTACLE_MAX_Y:-3.70}"
export COSMOS_VLN_MISSION_REQUIRED_ROUTE_ID="${ROUTE_ID}"
export COSMOS_VLN_MISSION_TIMEOUT_SEC="${COSMOS_VLN_MISSION_TIMEOUT_SEC:-1500}"
export COSMOS_VLN_ROUTE_NO_PROGRESS_SEC="${COSMOS_VLN_ROUTE_NO_PROGRESS_SEC:-45}"
export COSMOS_VLN_STAIR_MAX_HEADING="${COSMOS_VLN_STAIR_MAX_HEADING:-0.68}"
export COSMOS_VLN_NAV_MODE_ATTEMPTS="${COSMOS_VLN_NAV_MODE_ATTEMPTS:-4}"
export COSMOS_VLN_CONTINUOUS_ROUTE="${COSMOS_VLN_CONTINUOUS_ROUTE:-1}"
export COSMOS_VLN_CONTINUOUS_PASS_RADIUS="${COSMOS_VLN_CONTINUOUS_PASS_RADIUS:-0.68}"
export COSMOS_VLN_RAMP_MIN_ELEVATION_GAIN="${COSMOS_VLN_RAMP_MIN_ELEVATION_GAIN:-0.30}"
export COSMOS_VLN_RAMP_MIN_PITCH="${COSMOS_VLN_RAMP_MIN_PITCH:-0.07}"
export COSMOS_VLN_RAMP_CREST_MIN_Z="${COSMOS_VLN_RAMP_CREST_MIN_Z:-0.72}"
export COSMOS_VLN_RAMP_EXIT_MAX_Z="${COSMOS_VLN_RAMP_EXIT_MAX_Z:-0.58}"
export COSMOS_VLN_INFERENCE_TIMEOUT_SEC="${COSMOS_VLN_INFERENCE_TIMEOUT_SEC:-900}"
export COSMOS_VLN_VISUALIZATION_RVIZ="${COSMOS_VLN_VISUALIZATION_RVIZ:-0}"
export COSMOS_VLN_VISUALIZATION_IMAGE_WINDOW="${COSMOS_VLN_VISUALIZATION_IMAGE_WINDOW:-0}"

mkdir -p "${RUN_DIR}" "${LOG_DIR}"
source_ros

echo "[INFO] Starting external Go2-W runtime: ${RUNTIME_ROOT}"
"${RUNTIME_ROOT}/scripts/start_go2w_systemd.sh"
"${SCRIPT_DIR}/start_cosmos_vln_bridge.sh"
"${SCRIPT_DIR}/start_cosmos_vln_mission.sh"
echo "[OK] Extended Go2-W/Cosmos stack is running."
